<?php declare(strict_types=1);
// Actual runtime/controller/view with isolated native adapters and durable SQLite.
// This is not a browser login or a production/customer fixture.
define('MW_PATH',__DIR__);
$settings=['encryptionKey'=>base64_encode(str_repeat('k',32)),'schedulerProfile'=>['contract'=>'magic-smtp-policy-scheduler-v1','acceptance'=>'passed'],'approvedApiBases'=>['https://kumo.example.com/ui/api']];
$bindings=[];$scope='customer';$login=1;$sub=false;$subAllowed=true;$guest=false;$adminAllowed=true;$serverRows=[];$apiRows=[];$ownedCount=[];$notifications=[];
function app_param($name,$default=null){return $name==='magicsmtp.connect'?$GLOBALS['settings']:($name==='magicsmtp.policyBridges'?$GLOBALS['bindings']:$default);}
class CHttpException extends RuntimeException{public $statusCode;function __construct($code,$message){$this->statusCode=$code;parent::__construct($message,$code);}}
class CDbCriteria{public $params=[],$limit,$order,$condition;function addCondition($value){$this->condition=$value;}}
class Customer{public $customer_id,$customer_uid,$inactive_at='',$active=true,$options=[];function __construct($id){$this->customer_id=$id;$this->customer_uid='uid-'.$id;$this->options=['servers.max_delivery_servers'=>5];}static function model(){return new self(0);}function findByPk($id){return $GLOBALS['customers'][(int)$id]??null;}function getIsActive(){return $this->active;}function getGroupOption($name,$default){return $this->options[$name]??$default;}}
class DeliveryServer{static function model(){return new self;}function findAll($criteria){$id=(int)$criteria->params[':connectCustomer'];$legacy=[];foreach($GLOBALS['bindings']as$b)if((int)$b['customer_id']===$id)$legacy=array_merge($legacy,$b['server_ids']);return array_values(array_filter($GLOBALS['serverRows'],static function($row)use($id,$legacy){return $row->customer_id===$id||in_array($row->server_id,$legacy,true);}));}}
class DeliveryServerMagicSmtpWebApi{static function model(){return new self;}function findByPk($id){return $GLOBALS['apiRows'][$id]??null;}}
class FakeCommand{function queryScalar($args){return $GLOBALS['ownedCount'][$args[':c']]??0;}}
class FakeDb{public $tablePrefix='';public $pdo;function __construct($pdo){$this->pdo=$pdo;}function setActive($value){}function getPdoInstance(){return $this->pdo;}function createCommand($sql){return new FakeCommand;}}
class Yii{static function app(){return $GLOBALS['application'];}static function getPathOfAlias($alias){return false;}}
function customer(){return new class{public $isGuest;function __construct(){$this->isGuest=$GLOBALS['guest'];}function getId(){return $GLOBALS['login'];}};}
function is_subaccount(){return $GLOBALS['sub'];}function subaccount(){return new class{function customer(){return $GLOBALS['customers'][$GLOBALS['login']];}function canManageServers(){return $GLOBALS['subAllowed'];}};}
function apps(){return new class{function isAppName($name){return $GLOBALS['scope']===$name;}};}
function user(){return new class{public $isGuest=false;function getModel(){return new class{public $status='active',$user_id=91;function hasRouteAccess($route){return $GLOBALS['adminAllowed'];}};}};}
class FakeRequest{public $post=[],$query=[],$isPost=false,$csrfTokenName='native_csrf',$csrfToken='valid-native-csrf';function getIsPostRequest(){return $this->isPost;}function getPost($key,$default=null){return $this->post[$key]??$default;}function getQuery($key,$default=null){return $this->query[$key]??$default;}}
function request(){return $GLOBALS['request'];}function notify(){return new class{function addSuccess($message){$GLOBALS['notifications'][]=$message;}};}
class CHtml{static function encode($value){return htmlspecialchars($value,ENT_QUOTES,'UTF-8');}}
class ExtensionController{public $data,$rendered,$view;function setData($data){$this->data=$data;}function render($view,$args){$this->view=$view;extract($args);ob_start();require dirname(__DIR__).'/magicsmtp/views/connect.php';$this->rendered=ob_get_clean();}}
class ExtensionInit{function isAppName($name){return apps()->isAppName($name);}}
require dirname(__DIR__).'/magicsmtp/controllers/Magic_smtp_connectController.php';
require dirname(__DIR__).'/magicsmtp/MagicsmtpExt.php';
$pdo=new PDO('sqlite::memory:');$db=new FakeDb($pdo);$application=new class($db){public $db;function __construct($db){$this->db=$db;}function getDb(){return $this->db;}};
$store=MagicSmtpConnectRuntime::store();$store->install();$store->setEnabled(true,91,time());$request=new FakeRequest;
$customers=[];foreach([1,2,3]as$id)$customers[$id]=new Customer($id);
function check($value,$label){if(!$value)throw new RuntimeException($label);$GLOBALS['checks']=($GLOBALS['checks']??0)+1;}
function blocked(callable $run,int $status,string $label){try{$run();throw new RuntimeException('Unexpected allow: '.$label);}catch(CHttpException $e){check($e->statusCode===$status,$label);}}
function page(array $post=[],array $query=[]){$GLOBALS['request']->isPost=(bool)$post;$GLOBALS['request']->post=$post;$GLOBALS['request']->query=$query;$c=new Magic_smtp_connectController;$c->actionIndex();return $c;}
function row($id,$owner,$host,$type='magic-smtp-web-api'){$GLOBALS['serverRows'][]=(object)['server_id'=>$id,'customer_id'=>$owner,'name'=>'Synthetic <server '.$id.'>','type'=>$type,'status'=>'active'];$GLOBALS['apiRows'][$id]=(object)['hostname'=>$host,'disable_ssl'=>0,'password'=>'private-synthetic-key-'.$id];}
row(11,1,'https://kumo.example.com/ui/api/ingest/email');row(12,1,'http://malformed.example.com/ui/api/ingest/email');row(13,2,'https://kumo.example.com/ui/api/ingest/email');row(14,0,'https://kumo.example.com/ui/api/ingest/email');row(15,1,'https://else.example.com/ui/api/ingest/email');row(16,1,'smtp.example.com','smtp');
$c=page([],['customer_id'=>2]);check($c->view==='ext-magicsmtp.views.connect','normal extension view route');check(strpos($c->rendered,'#11')!==false&&strpos($c->rendered,'#13')===false,'customer ID comes from login');check(strpos($c->rendered,'#14')===false,'global unbound server excluded');check(strpos($c->rendered,'Synthetic &lt;server 11&gt;')!==false,'native view encodes names');check(strpos($c->rendered,'private-synthetic-key')===false,'no sending credentials in view');check(substr_count($c->rendered,'Not eligible for this connection')===3,'malformed wrongbase and SMTP rows remain visible ineligible');
$menu=(new MagicsmtpExt)->_connectMenu([]);check($menu['magic-smtp-connect']['route']===['magic_smtp_connect/index'],'normal native navigation route');
$guest=true;blocked(static function(){page();},403,'guest denied');$guest=false;$sub=true;$subAllowed=false;blocked(static function(){page();},403,'subaccount without server permission denied');check((new MagicsmtpExt)->_connectMenu([])===[],'restricted navigation excluded');$sub=false;$subAllowed=true;
blocked(static function(){page(['operation'=>'generate','native_csrf'=>'wrong']);},400,'POST CSRF denied before action');blocked(static function(){page(['operation'=>'enable','native_csrf'=>'valid-native-csrf']);},403,'customer cannot enable installation');
$customers[1]->active=false;blocked(static function(){page();},403,'inactive account denied');$customers[1]->active=true;$customers[1]->options['servers.max_delivery_servers']=0;blocked(static function(){page();},403,'delivery server entitlement required');$customers[1]->options['servers.max_delivery_servers']=5;
$scope='backend';$adminAllowed=false;blocked(static function(){page([],['customer_id'=>1]);},403,'backend exact role rights required');$adminAllowed=true;$c=page([],['customer_id'=>2]);check(strpos($c->rendered,'#13')!==false&&strpos($c->rendered,'#11')===false,'backend explicitly selects customer');check(strpos($c->rendered,'Enable customer connections')!==false,'admin normal page exposes installation action');$scope='customer';
// Existing and newly registered isolated adapters use the exact same route/view.
foreach([2=>'Existing edited sample',3=>'New sample connection']as$id=>$label){$customers[$id]->inactive_at=gmdate('Y-m-d H:i:s',time()+1800);$customers[$id]->options=['sending.quota'=>0,'servers.can_send_from_system_servers'=>'no','servers.max_delivery_servers'=>0];$store->query('INSERT INTO '.$store->table('demo').' VALUES(?,?,?,?,?)',[$id,'uid-'.$id,time()+1800,json_encode(['label'=>$label,'stage'=>'new','revision'=>0]),time()]);}
$before=$store->query('SELECT state_json FROM '.$store->table('demo').' WHERE customer_id=2')->fetchColumn();$store->install();check($store->query('SELECT state_json FROM '.$store->table('demo').' WHERE customer_id=2')->fetchColumn()===$before,'idempotent schema upgrade preserves existing demo edits');
foreach([2,3]as$id){$login=$id;$c=page();check(strpos($c->rendered,'Demonstration workspace.')!==false,'demo normal route '.$id);check(strpos($c->rendered,'private-synthetic-key')===false,'demo never lists live keys '.$id);$c=page(['operation'=>'generate','native_csrf'=>'valid-native-csrf','customer_id'=>1]);check(strpos($c->rendered,'DEMO-MAILWIZZ-PAIR')!==false,'shared zero-execution demo code '.$id);check((int)$store->query('SELECT COUNT(*) FROM '.$store->table('grant'))->fetchColumn()===0,'demo creates no real grant '.$id);$c=page(['operation'=>'demo-save','native_csrf'=>'valid-native-csrf','label'=>'Edited '.$id.' <safe>']);$c=page();check(strpos($c->rendered,'Edited '.$id.' &lt;safe&gt;')!==false,'demo edit reload durable and escaped '.$id);check(MagicSmtpConnectRuntime::demo($id)['state']['revision']===1,'demo revision persisted '.$id);try{MagicSmtpConnectRuntime::nativeServers($id);throw new RuntimeException('demo credential inventory allowed');}catch(RuntimeException $e){check($e->getCode()===403,'demo denies live credential inventory '.$id);}}
check(strpos($store->query('SELECT state_json FROM '.$store->table('demo').' WHERE customer_id=2')->fetchColumn(),'Edited 2')!==false,'second demo does not overwrite first');
$ownedCount[3]=1;blocked(static function(){page();},403,'demo real infrastructure drift denied');$ownedCount[3]=0;$customers[3]->options['sending.quota']=1;blocked(static function(){page();},403,'demo execution boundary drift denied');$customers[3]->options['sending.quota']=0;$store->query('UPDATE '.$store->table('demo').' SET expires_at=? WHERE customer_id=3',[time()-1]);blocked(static function(){page();},403,'admin demo expiry preserved');$login=2;$customers[2]->customer_uid='replaced-account';blocked(static function(){page();},403,'demo immutable account identity checked');
check((int)$store->query('SELECT COUNT(*) FROM '.$store->table('connection'))->fetchColumn()===0,'demo produced no production connection');
echo json_encode(['ok'=>true,'checks'=>$checks,'scope'=>'actual runtime/controller/view with isolated native adapters','existingAndNewDemoAdapters'=>true,'browserLoginVerified'=>false,'externalRequests'=>0,'realCustomerAccountsChanged'=>0],JSON_PRETTY_PRINT)."\n";
